name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  draftRelease:
    runs-on: ubuntu-latest

    name: Draft Release
    steps:
      - uses: actions/checkout@v2
      - name: Draft Release
        uses: toolmantim/release-drafter@v5.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
